Feature flash message
tatsuya4150/chat-space pull request #6
Opened 2017-01-24 10:46 UTC by tatsuya4150

# WHAT
- フラッシュメッセージの実装
- デザインの修正（font-awesome実装）

2017-01-24 23:42 UTC, hc0208 requested changes

2017-01-24 23:42 UTC, hc070208 commented on app/views/devise/registrations/edit.html.haml
> +s#account-page.account-page
sが入ってるw

2017-01-24 23:42 UTC, hc070208 commented on config/locales/devise.en.yml
> +      signed_out: "サインアウトできたよおおおお"
devise 日本語化で調べてみ！他の方法の方がいいと思う！

2017-01-25 05:50 UTC, hc070208 commented on config/locales/devise.en.yml
> +      signed_out: "サインアウトできたよおおおお"
英語に戻しといて笑

2017-01-25 08:15 UTC, tatsuya4150 commented on config/locales/devise.en.yml
> +      signed_out: "サインアウトできたよおおおお"
お恥ずかしい限りでございます笑

2017-01-25 13:55 UTC, hc070208 commented
LGTM

2017-01-26 02:19 UTC, merged